### ISSUE TITLE
Articulation of what the complex format is or how to convolve?

### ISSUE THREAD

**Issue by cnlohr** [JodiTheTigger/meow_fft#8]
I am confused by this comment. 
```
        // out[0].r == out[0  ].r
        // out[0].j == out[N/2].r
```

It would be helpful if there was more articulation in the documentation about what this means or how to convolve two real signals.

**Comment by cnlohr** [comment]
It looks like this would be the convolution.
```
		for( i = 0; i < N/2; i++ )
		{
			float ra = sig_fft[i].r;
			float ja = sig_fft[i].j;
			float rb = LFSRFFT[0][i].r;
			float jb = LFSRFFT[0][i].j;
			intermediate[i].r = ra * rb - ja * jb;
			intermediate[i].j = ra * jb + ja * rb;
		}
```

**Comment by JodiTheTigger** [comment]
The first and last item in a FFT of real numbers are _always_ real. 
And the size of the output FFT is normally the `input size + 1`

In order to have the output buffer be the same size as the input buffer, I move the N+1 real number into the imaginary component of index 0 to maintain the same input and output buffer size.

To convolve two real signals, from memory, you convert them to FFT, complex multiply each component, and then do an inverse FFT back.

Because of this little hack, you just need to special case index 0 and multiply it piecewise instead of as a complex number.

```
		intermediate[0].r = A[0].r * B[0].r;
		intermediate[0].j = A[0].j * B[0].j;

		for( i = 1; i < N/2; i++ )
		{
			float ra = A[i].r;
			float ja = A[i].j;
			float rb = B[i].r;
			float jb = B[i].j;
			intermediate[i].r = ra * rb - ja * jb;
			intermediate[i].j = ra * jb + ja * rb;
		}
```
